// Derive types from const arrays to avoid duplication
// Arrays are marked as const to enable type inference

export const directives = [
  "=",
  "ac68080",
  "align",
  "assert",
  "basereg",
  "blk",
  "bss",
  "bss_c",
  "bss_f",
  "cargs",
  "clrfo",
  "clrso",
  "cnop",
  "code",
  "code_c",
  "code_f",
  "comm",
  "comment",
  "cpu32",
  "cseg",
  "data",
  "data_c",
  "data_f",
  "dc",
  "dcb",
  "dr",
  "ds",
  "dseg",
  "dw",
  "dx",
  "echo",
  "einline",
  "else",
  "elseif",
  "elif",
  "end",
  "endb",
  "endc",
  "endif",
  "endm",
  "endr",
  "equ",
  "equr",
  "equrl",
  "erem",
  "even",
  "fail",
  "far",
  "fequr",
  "fequrl",
  "fequ",
  "fo",
  "fpu",
  "freg",
  "idnt",
  "if",
  "if1",
  "if2",
  "ifc",
  "ifd",
  "ifeq",
  "ifge",
  "ifgt",
  "ifle",
  "iflt",
  "ifb",
  "ifnb",
  "ifnc",
  "ifnd",
  "ifne",
  "ifmacrod",
  "ifmacrond",
  "ifp1",
  "iif",
  "incbin",
  "incdir",
  "include",
  "initnear",
  "inline",
  "list",
  "llen",
  "local",
  "machine",
  "macro",
  "mc68000",
  "mc68010",
  "mc68020",
  "mc68030",
  "mc68040",
  "mc68060",
  "mcf5202",
  "mcf5204",
  "mcf5206",
  "mcf5208",
  "mcf5307",
  "mcf5407",
  "mcf5470",
  "mcf5471",
  "mcf5472",
  "mcf5473",
  "mcf5474",
  "mcf5475",
  "mexit",
  "msource",
  "near",
  "nolist",
  "nopage",
  "nref",
  "odd",
  "offset",
  "opt",
  "org",
  "output",
  "page",
  "plen",
  "printt",
  "printv",
  "public",
  "popsection",
  "pushsection",
  "reg",
  "rem",
  "rept",
  "rorg",
  "rs",
  "rseven",
  "rsreset",
  "rsset",
  "sdreg",
  "section",
  "set",
  "setfo",
  "setso",
  "showoffset",
  "so",
  "spc",
  "text",
  "ttl",
  "weak",
  "xdef",
  "xref",
] as const;

export type Directive = (typeof directives)[number];

export function isDirective(mnemonic: string): mnemonic is Directive {
  return directives.includes(mnemonic as Directive);
}

export const instructions = [
  "abcd",
  "add",
  "adda",
  "addi",
  "addq",
  "addx",
  "and",
  "andi",
  "asl",
  "asr",
  "bcc",
  "bchg",
  "bclr",
  "bcs",
  "beq",
  "bfchg",
  "bfclr",
  "bfexts",
  "bfextu",
  "bfffo",
  "bfins",
  "bfset",
  "bftst",
  "bge",
  "bgnd",
  "bgt",
  "bhi",
  "bhs",
  "bitrev",
  "bkpt",
  "ble",
  "blo",
  "bls",
  "blt",
  "bmi",
  "bne",
  "bpl",
  "bra",
  "bset",
  "bsr",
  "btst",
  "bvc",
  "bvs",
  "byterev",
  "callm",
  "cas",
  "cas2",
  "chk",
  "chk2",
  "cinva",
  "cinvl",
  "cinvp",
  "clr",
  "cmp",
  "cmp2",
  "cmpa",
  "cmpi",
  "cmpm",
  "cpusha",
  "cpushl",
  "cpushp",
  "dbcc",
  "dbcs",
  "dbeq",
  "dbf",
  "dbge",
  "dbgt",
  "dbhi",
  "dbhs",
  "dble",
  "dblo",
  "dbls",
  "dblt",
  "dbmi",
  "dbne",
  "dbpl",
  "dbra",
  "dbt",
  "dbvc",
  "dbvs",
  "divs",
  "divsl",
  "divu",
  "divul",
  "eor",
  "eori",
  "exg",
  "ext",
  "extb",
  "fabs",
  "facos",
  "fadd",
  "fasin",
  "fatan",
  "fatanh",
  "fbeq",
  "fbf",
  "fbge",
  "fbgl",
  "fbgle",
  "fbgt",
  "fble",
  "fblt",
  "fbne",
  "fbnge",
  "fbngl",
  "fbngle",
  "fbngt",
  "fbnle",
  "fbnlt",
  "fboge",
  "fbogl",
  "fbogt",
  "fbole",
  "fbolt",
  "fbor",
  "fbseq",
  "fbsf",
  "fbsne",
  "fbst",
  "fbt",
  "fbueq",
  "fbuge",
  "fbugt",
  "fbule",
  "fbult",
  "fbun",
  "fcmp",
  "fcos",
  "fcosh",
  "fdabs",
  "fdadd",
  "fdbeq",
  "fdbf",
  "fdbge",
  "fdbgl",
  "fdbgle",
  "fdbgt",
  "fdble",
  "fdblt",
  "fdbne",
  "fdbnge",
  "fdbngl",
  "fdbngle",
  "fdbngt",
  "fdbnle",
  "fdbnlt",
  "fdboge",
  "fdbogl",
  "fdbogt",
  "fdbole",
  "fdbolt",
  "fdbor",
  "fdbseq",
  "fdbsf",
  "fdbsne",
  "fdbst",
  "fdbt",
  "fdbueq",
  "fdbuge",
  "fdbugt",
  "fdbule",
  "fdbult",
  "fdbun",
  "fddiv",
  "fdiv",
  "fdmove",
  "fdmul",
  "fdneg",
  "fdsqrt",
  "fdsub",
  "fetox",
  "fetoxm1",
  "ff1",
  "fgetexp",
  "fgetman",
  "fint",
  "fintrz",
  "flog10",
  "flog2",
  "flogn",
  "flognp1",
  "fmod",
  "fmove",
  "fmovecr",
  "fmovem",
  "fmul",
  "fneg",
  "fnop",
  "frem",
  "frestore",
  "fsabs",
  "fsadd",
  "fsave",
  "fscale",
  "fsdiv",
  "fseq",
  "fsf",
  "fsge",
  "fsgl",
  "fsgldiv",
  "fsgle",
  "fsglmul",
  "fsgt",
  "fsin",
  "fsincos",
  "fsinh",
  "fsle",
  "fslt",
  "fsmove",
  "fsmul",
  "fsne",
  "fsneg",
  "fsnge",
  "fsngl",
  "fsngle",
  "fsngt",
  "fsnle",
  "fsnlt",
  "fsoge",
  "fsogl",
  "fsogt",
  "fsole",
  "fsolt",
  "fsor",
  "fsqrt",
  "fsseq",
  "fssf",
  "fssne",
  "fssqrt",
  "fsst",
  "fssub",
  "fst",
  "fsub",
  "fsueq",
  "fsuge",
  "fsugt",
  "fsule",
  "fsult",
  "fsun",
  "ftan",
  "ftanh",
  "ftentox",
  "ftrapeq",
  "ftrapf",
  "ftrapge",
  "ftrapgl",
  "ftrapgle",
  "ftrapgt",
  "ftraple",
  "ftraplt",
  "ftrapne",
  "ftrapnge",
  "ftrapngl",
  "ftrapngle",
  "ftrapngt",
  "ftrapnle",
  "ftrapnlt",
  "ftrapoge",
  "ftrapogl",
  "ftrapogt",
  "ftrapole",
  "ftrapolt",
  "ftrapor",
  "ftrapseq",
  "ftrapsf",
  "ftrapsne",
  "ftrapst",
  "ftrapt",
  "ftrapueq",
  "ftrapuge",
  "ftrapugt",
  "ftrapule",
  "ftrapult",
  "ftrapun",
  "ftst",
  "ftwotox",
  "halt",
  "illegal",
  "intouch",
  "jbcc",
  "jbcs",
  "jbeq",
  "jbge",
  "jbgt",
  "jbhi",
  "jbhs",
  "jble",
  "jblo",
  "jbls",
  "jblt",
  "jbmi",
  "jbne",
  "jbpl",
  "jbra",
  "jbsr",
  "jbvc",
  "jbvs",
  "jmp",
  "jsr",
  "lea",
  "line_a",
  "line_f",
  "linea",
  "linef",
  "link",
  "lpstop",
  "lsl",
  "lsr",
  "maaac",
  "mac",
  "masac",
  "mov3q",
  "movclr",
  "move",
  "move16",
  "movea",
  "movec",
  "movem",
  "movep",
  "moveq",
  "moves",
  "movm",
  "msaac",
  "msac",
  "mssac",
  "muls",
  "mulu",
  "mvs",
  "mvz",
  "nbcd",
  "neg",
  "negx",
  "nop",
  "not",
  "or",
  "ori",
  "pack",
  "pbac",
  "pbas",
  "pbbc",
  "pbbs",
  "pbcc",
  "pbcs",
  "pbgc",
  "pbgs",
  "pbic",
  "pbis",
  "pblc",
  "pbls",
  "pbsc",
  "pbss",
  "pbwc",
  "pbws",
  "pdbac",
  "pdbas",
  "pdbbc",
  "pdbbs",
  "pdbcc",
  "pdbcs",
  "pdbgc",
  "pdbgs",
  "pdbic",
  "pdbis",
  "pdblc",
  "pdbls",
  "pdbsc",
  "pdbss",
  "pdbwc",
  "pdbws",
  "pea",
  "pflush",
  "pflusha",
  "pflushan",
  "pflushn",
  "pflushr",
  "pflushs",
  "ploadr",
  "ploadw",
  "plpar",
  "plpaw",
  "pmove",
  "pmovefd",
  "prestore",
  "psac",
  "psas",
  "psave",
  "psbc",
  "psbs",
  "pscc",
  "pscs",
  "psgc",
  "psgs",
  "psic",
  "psis",
  "pslc",
  "psls",
  "pssc",
  "psss",
  "pswc",
  "psws",
  "ptestr",
  "ptestw",
  "ptrapac",
  "ptrapas",
  "ptrapbc",
  "ptrapbs",
  "ptrapcc",
  "ptrapcs",
  "ptrapgc",
  "ptrapgs",
  "ptrapic",
  "ptrapis",
  "ptraplc",
  "ptrapls",
  "ptrapsc",
  "ptrapss",
  "ptrapwc",
  "ptrapws",
  "pulse",
  "pvalid",
  "rems",
  "remu",
  "reset",
  "rol",
  "ror",
  "roxl",
  "roxr",
  "rtd",
  "rte",
  "rtm",
  "rtr",
  "rts",
  "sats",
  "sbcd",
  "scc",
  "scs",
  "seq",
  "sf",
  "sge",
  "sgt",
  "shi",
  "shs",
  "sle",
  "slo",
  "sls",
  "slt",
  "smi",
  "sne",
  "spl",
  "st",
  "stop",
  "strldsr",
  "sub",
  "suba",
  "subi",
  "subq",
  "subx",
  "svc",
  "svs",
  "swap",
  "tas",
  "tbls",
  "tblsn",
  "tblu",
  "tblun",
  "tpf",
  "trap",
  "trapcc",
  "trapcs",
  "trapeq",
  "trapf",
  "trapge",
  "trapgt",
  "traphi",
  "traphs",
  "traple",
  "traplo",
  "trapls",
  "traplt",
  "trapmi",
  "trapne",
  "trappl",
  "trapt",
  "trapv",
  "trapvc",
  "trapvs",
  "tst",
  "unlk",
  "unpk",
  "wddata",
  "wdebug",
] as const;

export type Instruction = (typeof instructions)[number];

export function isInstruction(mnemonic: string): mnemonic is Instruction {
  return instructions.includes(mnemonic as Instruction);
}

// Mnemonics that never take operands (instructions and directives)
// This helps distinguish positional comments from operands
export const noOperand: (Instruction | Directive)[] = [
  // CPU instructions
  "illegal",
  "nop",
  "reset",
  "rte",
  "rtr",
  "rts",
  "trapv",
  // Assembler directives
  "clrfo",
  "clrso",
  "comment",
  "einline",
  "else",
  "end",
  "endc",
  "endif",
  "endm",
  "endr",
  "erem",
  "even",
  "inline",
  "list",
  "mexit",
  "nolist",
  "nopage",
  "odd",
  "page",
  "popsection",
  "pushsection",
  "rem",
  "rsreset",
] as const;

export const dataRegisters = [
  "d0",
  "d1",
  "d2",
  "d3",
  "d4",
  "d5",
  "d6",
  "d7",
] as const;

export type DataRegister = (typeof dataRegisters)[number];

export function isDataRegister(reg: string): reg is DataRegister {
  return dataRegisters.includes(reg as DataRegister);
}

export const addressRegisters = [
  "a0",
  "a1",
  "a2",
  "a3",
  "a4",
  "a5",
  "a6",
  "a7",
  "sp",
] as const;

export type AddressRegister = (typeof addressRegisters)[number];

export function isAddressRegister(reg: string): reg is AddressRegister {
  return addressRegisters.includes(reg as AddressRegister);
}

export const specialRegisters = [
  "sr",
  "ccr",
  "usp",
  "ssp",
  "pc",
  "vbr",
  "sfc",
  "dfc",
  "cacr",
  "caar",
] as const;

export type SpecialRegister = (typeof specialRegisters)[number];

export function isSpecialRegister(reg: string): reg is SpecialRegister {
  return specialRegisters.includes(reg as SpecialRegister);
}

// FPU registers (68881/68882/68040+)
export const fpuDataRegisters = [
  "fp0",
  "fp1",
  "fp2",
  "fp3",
  "fp4",
  "fp5",
  "fp6",
  "fp7",
] as const;

export type FPUDataRegister = (typeof fpuDataRegisters)[number];

export function isFPUDataRegister(reg: string): reg is FPUDataRegister {
  return fpuDataRegisters.includes(reg as FPUDataRegister);
}

export const fpuControlRegisters = ["fpcr", "fpsr", "fpiar"] as const;

export type FPUControlRegister = (typeof fpuControlRegisters)[number];

export function isFPUControlRegister(reg: string): reg is FPUControlRegister {
  return fpuControlRegisters.includes(reg as FPUControlRegister);
}

export type FPURegister = FPUDataRegister | FPUControlRegister;

export function isFPURegister(reg: string): reg is FPURegister {
  return isFPUDataRegister(reg) || isFPUControlRegister(reg);
}

export type Register =
  | DataRegister
  | AddressRegister
  | SpecialRegister
  | FPURegister;

export function isRegister(reg: string): reg is Register {
  return (
    isDataRegister(reg) ||
    isAddressRegister(reg) ||
    isSpecialRegister(reg) ||
    isFPURegister(reg)
  );
}

export const builtinSymbols = [
  "__RS",
  "__SO",
  "__FO",
  "REPTN",
  "CARG",
  "NARG",
  "__G2",
  "__LK",
  "__CPU",
  "__FPU",
  "__MMU",
  "__OPTC",
  "_MOVEMBYTES",
  "__MOVEMREGS",
  "__VASM",
] as const;

export type BuiltinSymbol = (typeof builtinSymbols)[number];

export function isBuiltinSymbol(symbol: string): symbol is BuiltinSymbol {
  return builtinSymbols.includes(symbol as BuiltinSymbol);
}

export const sizes = ["b", "w", "l", "s", "d", "x", "p", "q"] as const;

export type Size = (typeof sizes)[number];

export function isSize(size: string): size is Size {
  return sizes.includes(size as Size);
}

export const addressSizes = ["w", "l"] as const;
export type AddressSize = (typeof addressSizes)[number];
export function isAddressSize(size: string): size is AddressSize {
  return addressSizes.includes(size as AddressSize);
}

export const binaryOps = [
  "+",
  "-",
  "*",
  "/",
  "%",
  "&",
  ",",
  "^",
  "<<",
  ">>",
  "&&",
  ",,",
  "=",
  "<>",
  "<",
  ">",
  "<=",
  ">=",
  "~",
  "|",
  "!",
  "//",
  "==",
  "!=",
  "||",
] as const;
export type BinaryOp = (typeof binaryOps)[number];
export function isBinaryOp(op: string): op is BinaryOp {
  return binaryOps.includes(op as BinaryOp);
}

export const unaryOps = ["+", "-", "~", "!"];
export type UnaryOp = (typeof unaryOps)[number];
export function isUnaryOp(op: string): op is UnaryOp {
  return unaryOps.includes(op as UnaryOp);
}

export const memoryTypes = ["fast", "chip"] as const;
export type MemoryType = (typeof memoryTypes)[number];
export function isMemoryType(type: string): type is MemoryType {
  return memoryTypes.includes(type as MemoryType);
}

export const sectionTypes = ["code", "data", "bss"] as const;
export type SectionType = (typeof sectionTypes)[number];
export function isSectionType(type: string): type is SectionType {
  return sectionTypes.includes(type as SectionType);
}

/**
 * Directives that open a block, mapped to the directives that close it.
 *
 * Conditionals accept either spelling of their terminator. Every conditional
 * opener is spelled `if` something.
 */
export const blockOpeners: Record<string, readonly string[]> = {
  macro: ["endm"],
  rept: ["endr"],
  if: ["endc", "endif"],
  ifeq: ["endc", "endif"],
  ifne: ["endc", "endif"],
  ifgt: ["endc", "endif"],
  ifge: ["endc", "endif"],
  iflt: ["endc", "endif"],
  ifle: ["endc", "endif"],
  ifb: ["endc", "endif"],
  ifnb: ["endc", "endif"],
  if1: ["endc", "endif"],
  if2: ["endc", "endif"],
  ifp1: ["endc", "endif"],
  ifc: ["endc", "endif"],
  ifnc: ["endc", "endif"],
  ifd: ["endc", "endif"],
  ifnd: ["endc", "endif"],
  ifmacrod: ["endc", "endif"],
  ifmacrond: ["endc", "endif"],
};

/** Directives that end one arm of a conditional and begin the next. */
export const blockAlternatives = new Set(["else", "elseif"]);

/** Every directive that closes a block. */
export const blockTerminators = new Set(["endm", "endr", "endc", "endif"]);
